sudo: required
services:
  - docker

before_install:
  - docker build -t colincoins/react-test -f ./client/Dockerfile.dev ./client
  # docker build other project
script:
  - docker run colincoins/react-test npm test -- --coverage
  # docker run other project

after_success:
  - docker build -t colincoins/multi-client ./client
  - docker build -t colincoins/multi-nginx ./nginx
  - docker build -t colincoins/multi-server ./server
  - docker build -t colincoins/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push colincoins/multi-client
  - docker push colincoins/multi-nginx
  - docker push colincoins/multi-server
  - docker push colincoins/multi-worker
  